"""Single source of truth for slash-command descriptions, shared by the decorators and /help."""

LEADERBOARD = "Check standings, filter by format, color or set"
STATS = "Check your stats or a player by name or set code"
JOIN = "Join the leaderboard with your 17lands profile"
OPT_OUT = "Hide your rank, keep your profile and trophies"
RETIRE = "Pause and hide everything until you come back"
EXILE = "Permanently delete your data"
HELP = "See the commands available here"
LINK_17LANDS = "Link or update 17lands, leaderboard optional"
LINK_ARENA_LOBBY = "Set your MTG Arena handle"
LINK_ARENA = f"{LINK_ARENA_LOBBY} for Pod Drafts"
POD_READY = "Initiate a Draftmancer Ready Check"
POD_START = "Start the draft now, skipping the ready check"
POD_SETTINGS = "Change a pod's format and pairings"
POD_TAKEOVER = "Take ownership of the Draftmancer session"
POD_SEEDING = "Get leaderboard standings of players on a pod thread"
POD_STANDINGS = "Post the standings embed for a pod-draft event"
POD_CHAMPION = "[Admin] Post the champion announcement for a completed pod-draft event"
POD_BACKFILL = "[Admin] Reconstruct a pod-draft event from its thread"
POD_SCHEDULE = "[Admin] Preview and post this week's pod-draft schedule"
PREVIEW_SEASON_AWARDS = "[Admin] Award the best preview season posts by crowd reaction"
