"""Add player_accounts and draft_events.account_id

Revision ID: bb93321e99da
Revises: e2a7f1b9c6d4
Create Date: 2026-06-22 18:45:07.421225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb93321e99da'
down_revision: Union[str, None] = 'e2a7f1b9c6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'name', name='uq_player_account')
    )
    op.add_column('draft_events', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_draft_events_account_id', 'draft_events', 'player_accounts',
        ['account_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_draft_events_account_id', 'draft_events', type_='foreignkey')
    op.drop_column('draft_events', 'account_id')
    op.drop_table('player_accounts')
    # ### end Alembic commands ###
