"""Add pod_signals + pod_signal_members for on-demand pods

Revision ID: d8ffcbcda5ba
Revises: h9i0j1k2l3m4
Create Date: 2026-07-13 02:31:37.285233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ffcbcda5ba'
down_revision: Union[str, None] = 'h9i0j1k2l3m4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pod_signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('slot_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), server_default='open', nullable=False),
    sa.Column('opened_by', sa.String(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('nudged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['pod_draft_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'bucket', name='uq_pod_signal_message_bucket')
    )
    op.create_index('ix_pod_signals_status', 'pod_signals', ['status'], unique=False)
    op.create_table('pod_signal_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('discord_user_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['pod_signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', 'discord_user_id', name='uq_pod_signal_member')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pod_signal_members')
    op.drop_index('ix_pod_signals_status', table_name='pod_signals')
    op.drop_table('pod_signals')
    # ### end Alembic commands ###
